// Copies the post fonts (Cyrillic, Latin and Lithuanian letters; regular and bold) from
// @fontsource packages into public/fonts and writes src/fonts.css.
// Usage: install the @fontsource packages listed in FONTS (packages/shared/src/posts.ts)
// in any folder, then run: node scripts/build-fonts.mjs <that folder>/node_modules/@fontsource
import { copyFileSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const src = process.argv[2];
const root = new URL('..', import.meta.url).pathname;
const shared = readFileSync(join(root, '../../packages/shared/src/posts.ts'), 'utf8');
const fonts = [...shared.matchAll(/^\s+'?([a-z0-9-]+)'?: \{ family: '([^']+)', group/gm)].map(
  (m) => ({ key: m[1], family: m[2] }),
);
const SUBSETS = ['cyrillic', 'latin', 'latin-ext'];
mkdirSync(join(root, 'public/fonts'), { recursive: true });
let css = '/* Generated by scripts/build-fonts.mjs — fonts under the SIL Open Font License. */\n';
for (const { key, family } of fonts) {
  const dir = join(src, key);
  const files = readdirSync(join(dir, 'files'));
  const weights = [
    ...new Set(files.map((f) => f.match(/-(\d+)-normal\.woff2$/)?.[1]).filter(Boolean)),
  ]
    .map(Number)
    .sort((a, b) => a - b);
  const pick = [
    weights.includes(400) ? 400 : weights[0],
    weights.includes(700) ? 700 : weights.at(-1),
  ].filter((w, i, a) => a.indexOf(w) === i);
  for (const weight of pick) {
    for (const subset of SUBSETS) {
      const file = `${key}-${subset}-${weight}-normal.woff2`;
      if (!files.includes(file)) continue;
      // The unicode-range of each subset is in the package's combined stylesheet.
      const all = readFileSync(join(dir, `${weight}.css`), 'utf8');
      const block = all
        .split('/* ')
        .find((b) => b.startsWith(`${key}-${subset}-${weight}-normal */`));
      const range = block?.match(/unicode-range:\s*([^;]+);/)?.[1];
      if (!range) throw new Error(`no unicode-range for ${file}`);
      copyFileSync(join(dir, 'files', file), join(root, 'public/fonts', file));
      css += `@font-face{font-family:'${family}';font-style:normal;font-weight:${weight};font-display:swap;src:url(/fonts/${file}) format('woff2');unicode-range:${range}}\n`;
    }
  }
}
writeFileSync(join(root, 'src/fonts.css'), css);
console.log(`${fonts.length} fonts`);
